---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
  namespace: a2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: apache:a2
        imagePullPolicy: IfNotPresent
        name: apache
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: a2
spec:
  selector:
    app: apache
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  type: NodePort        
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: a2  