---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
  namespace: a2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: tomcat:8.5-a2
        imagePullPolicy: IfNotPresent
        name: tomcat
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: a2
spec:
  selector:
    app: tomcat
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8080
  type: NodePort        
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: a2